version: '3'

services:
  weather:
    container_name: goademo
    build:
      context: $GOPATH/src/github.com/penkovski/goademo
      dockerfile: Dockerfile.dev
    volumes:
      - "$GOPATH/src/github.com/penkovski/goademo/:/go/src/github.com/penkovski/goademo/"
    environment:
      HTTP_HOST: ""
      HTTP_PORT: "8080"
      OPENWEATHER_ADDR: "https://openweathermap.org/api"
      OPENWEATHER_APIKEY: "deadbeef"
    ports:
      - "8080:8080"
