FROM golang:1.16.5

RUN go install github.com/canthefason/go-watcher/cmd/watcher@latest

ADD . /go/src/github.com/penkovski/goademo/

WORKDIR /go/src/github.com/penkovski/goademo/

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "/go/bin/watcher -run github.com/penkovski/goademo/cmd/weather -watch github.com/penkovski/goademo/"]
